name: Codespell

on:
  push:
    branches: [theme-change]
  pull_request:
    branches: [theme-change]

permissions:
  contents: read

jobs:
  codespell:
    name: Check spelling
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install codespell
        run: pip install codespell
      - name: Run codespell
        run: codespell --skip="*.lock" --ignore-words-list="liste" .
